exclude = [
  'https://github.com/ajs/jumpnbump',
  'https://github.com/cabbagesandkings/cabbagesandkings',
  'https://github.com/cartlife/cartlife',
  'https://github.com/danielest/CaptainBlood',
  'https://github.com/davidgiven/cadaver',
  'https://github.com/DraknekGames/VGAGolf',
  'https://github.com/efornara/fractured',
  'https://github.com/fd0/pioneers',
  'https://github.com/freechessclub/freechess',
  'https://github.com/gloomydungeons/gloomydungeons',
  'https://github.com/ian-albert/tis-100',
  'https://github.com/ihsanullah/WebChess',
  'https://github.com/jeff-1amstudios/xargon',
  'https://github.com/jetpacapp/jet-story',
  'https://github.com/jsettlers/Islanders',
  'https://github.com/ljw1004/cotw',
  'https://github.com/mcneight/vultures-eye',
  'https://github.com/merlin91/goblin-camp',
  'https://github.com/ndee/websoccer',
  'https://github.com/OnlyLeigh/YetAnotherPixelDungeon',
  'https://github.com/OpenBound/OpenBound',
  'https://github.com/rioki/wastesedge',
  'https://github.com/sergejsha/WAtomic',
  'https://github.com/Siedler2/OpenSiedler',
  'https://github.com/tepidstream/faur',
  'https://github.com/TripleTriad/triad',
  'https://github.com/tycho/turtle-arena',
  'https://github.com/war1/war1',
  'https://github.com/warcraft-remake/warcraft-remake',
  'https://github.com/webfun-game/webfun',
  'https://github.com/wolfpackempire/wolfpack',
  'https://github.com/Xevil/Xevil',
  'https://gitlab.com/re-volt/rvgl',
]
